### ISSUE TITLE
Prisma server instructions result in failure in react-urql tutorial

### ISSUE THREAD

**Issue by sohara** [howtographql/howtographql#1020]
I've followed the server setup instructions for the react-urql tutorial and there seems to be an issue. I get the following results when I run `yarn prisma deploy`:

```sh
yarn run v1.17.3
$ prisma deploy
? Set up a new Prisma server or deploy to an existing server? Demo server + MySQL database
? Choose the region of your demo server sean-ohara-a1b542/demo-us1
? Choose a name for your service blahblah
? Choose a name for your stage dev

Written endpoint `https://us1.prisma.sh/sean-ohara-a1b542/blahblah/dev` to prisma.yml

Creating stage dev for service blahblah ✔
Deploying service `blahblah` to stage `dev` to server `prisma-us1` 1.0s

Changes:

  Link (Type)
  + Created type `Link`
  + Created field `id` of type `ID!`
  + Created field `createdAt` of type `DateTime!`
  + Created field `description` of type `String!`
  + Created field `url` of type `String!`
  + Created field `postedBy` of type `User`
  + Created field `votes` of type `[Vote!]!`

  User (Type)
  + Created type `User`
  + Created field `id` of type `ID!`
  + Created field `name` of type `String!`
  + Created field `email` of type `String!`
  + Created field `password` of type `String!`
  + Created field `links` of type `[Link!]!`
  + Created field `votes` of type `[Vote!]!`

  Vote (Type)
  + Created type `Vote`
  + Created field `id` of type `ID!`
  + Created field `link` of type `Link!`
  + Created field `user` of type `User!`

  UserToVote (Relation)
  + Created an inline relation between `User` and `Vote` in the column `user` of table `Vote`

  LinkToVote (Relation)
  + Created an inline relation between `Link` and `Vote` in the column `link` of table `Vote`

  LinkToUser (Relation)
  + Created an inline relation between `Link` and `User` in the column `postedBy` of table `Link`

Applying changes 1.8s

post-deploy:
 ▸    Cannot use GraphQLNonNull "LinkWhereUniqueInput!" from another module or
 ▸    realm.
 ▸    
 ▸    Ensure that there is only one instance of "graphql" in the node_modules
 ▸    directory. If different versions of "graphql" are the dependencies of
 ▸    other
 ▸    relied on modules, use "resolutions" to ensure only one version is
 ▸    installed.
 ▸    
 ▸    https://yarnpkg.com/en/docs/selective-version-resolutions
 ▸    
 ▸    Duplicate "graphql" modules cannot be used at the same time since
 ▸    different
 ▸    versions may have different capabilities and behavior. The data from one
 ▸    version used in the function from another could produce confusing and
 ▸    spurious results.

Get in touch if you need help: https://spectrum.chat/prisma
To get more detailed output, run $ export DEBUG="*"

Running prisma generate...

Generating schema... 27ms
Running prisma generate ✖
Warning: The `prisma generate` command was executed twice. Since Prisma 1.31, the Prisma client is generated automatically after running `prisma deploy`. It is not necessary to generate it via a `post-deploy` hook any more, you can therefore remove the hook if you do not need it otherwise.
Generating schema 35ms
 ▸    Cannot use GraphQLNonNull "LinkWhereUniqueInput!" from another module or realm.
 ▸    
 ▸    Ensure that there is only one instance of "graphql" in the node_modules
 ▸    directory. If different versions of "graphql" are the dependencies of other
 ▸    relied on modules, use "resolutions" to ensure only one version is installed.
 ▸    
 ▸    https://yarnpkg.com/en/docs/selective-version-resolutions
 ▸    
 ▸    Duplicate "graphql" modules cannot be used at the same time since different
 ▸    versions may have different capabilities and behavior. The data from one
 ▸    version used in the function from another could produce confusing and
 ▸    spurious results.

Get in touch if you need help: https://spectrum.chat/prisma
To get more detailed output, run $ export DEBUG="*"
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

If I try to continue with the tutorial by running `yarn start` and issue the test mutation, I get the following response:
```
{
  "data": null,
  "errors": [
    {
      "message": "Variable '$data' expected value of type 'LinkCreateInput!' but got: {\"url\":\"http://blah.ca\",\"description\":\"Very blah blah\",\"votes\":[],\"postedBy\":{}}. Reason: 'votes' Expected 'VoteCreateManyWithoutLinkInput', found not an object. (line 1, column 11):\nmutation ($data: LinkCreateInput!) {\n          ^",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "post"
      ]
    }
  ]
}
```

**Comment by sohara** [comment]
cc @kitten @JoviDeCroock

**Comment by JoviDeCroock** [comment]
Have you installed the dependencies inside the folder (and installed it with `yarn`)?

**Comment by sohara** [comment]
Yes. I've also cleared the `server` directory and reinstall everything to try again. I got the same results.

**Comment by kitten** [comment]
@sohara Hiya :wave: sorry about that! I think we've accidentally removed a resolution from the `package.json`. I've pushed a commit and if you update your server directory, it should work again: https://github.com/howtographql/react-urql/commit/f37c645346b0a5b88360ebe4343148a3fb40f4a0

**Comment by sohara** [comment]
Thanks @kitten. That update fixed the resolution issue and I'm no longer getting any errors on `yarn prisma deploy`. 

However, I am still getting errors when I try to issue the mutations. I think maybe some things have changed with package versions.

The instructions state: 
> Copy the following two mutations into the editor pane - make sure to have the default Playground from the app project selected in the left side-menu:

In my version graphql playground there is no left-menu from which to select the default playground.

I also noticed this part of the instructions:

> The yarn start executes the start script defined in package.json. The script first starts the server (which is then running on http://localhost:4000) and then opens up a GraphQL Playground for you to explore and work with the API.

It seems to imply that the script will open up a browser window automatically. That didn't happen for me. And one of your screenshots shows a bearer token header. Mine graphql playground wasn't populated with that automatically. Maybe some steps are missing?

**Comment by JoviDeCroock** [comment]
The mutations should now work, sorry for the inconvenience @sohara

**Comment by bruqui** [comment]
Just wanted to throw out there I had the same exact problem today and wanted to point that out. Maybe the tar needs to be updated on the curl command?

**Comment by itofficeeu** [comment]
Is this issue ready to be closed ?...

**Comment by alejandroiglesias** [comment]
I also had this issue today. Do you need to update the tar on the curl command as @bruqui pointed out?
