### ISSUE TITLE
Subscriptions not working (graphql.js - Subscriptions)

### ISSUE THREAD

**Issue by Musbell** [howtographql/howtographql#456]
Subscriptions not working after sending subscribed mutations i.e. **newLink** and **newVote**

**Comment by iquabius** [comment]
It didn't work for me either.

**Comment by azizuysal** [comment]
Ditto.

**Comment by nyoung697** [comment]
I was able to get it working by removing the where clause in the Subscription.js file:

    const newLink = {
      subscribe: async (parent, args, ctx, info) => {
        return ctx.db.subscription.link(
          { },
          info
        )
      },
    }

I'm not sure why that mutation_in isn't working...  Haven't had a chance to dig around.

**Comment by nntai** [comment]
It's not working for me too
Follow issue on prisma: https://github.com/graphcool/prisma/issues/1734

**Comment by eyal0803** [comment]
Looks like there was a PR (#475) which fixed the backend tutorial.
Anyway, like @nyoung697 sayd, just remove the `where` clause.

**Comment by thelovesmith** [comment]
```
function newVoteSubscribe(parent, args, context, info) {
    return context.prisma.$subscribe.vote({ 
        mutation_in: ['CREATED'] 
    }).node()
}

const newVote = {
    subscribe: newVoteSubscribe,
    resolve: payload => {
        return payload
    },
}
```

for some reason this code keeps giving me an error in the playground, it keeps returning "context.prisma.$subscribe.vote" is not a function

**Comment by swcarlosrj** [comment]
Thanks @Musbell for opening this issue 😄. It should be fixed. Closing this!

**Comment by gentleShark** [comment]
@swcarlosrj the newVote subscription still doesn't work like @thelovesmith mentioned. newVote is a recognized subscription in the playground but the vote() function is not created by prisma on the $subsciption object...thus the resolver fails with the error: "message": "context.prisma.$subscribe.vote is not a function" 

I wonder if the problem is related to Vote being a lookup table?

**Comment by jonatasbaldin** [comment]
Hey @swcarlosrj, can you take a look on this?

**Comment by rootandleaves** [comment]
same problem..any solution ?

**Comment by blacksrc** [comment]
If you are following the howtographql.com tutorial. Make sure that,
```
type Vote {
  id: ID! @id
  link: Link!
  user: User!
}
```
exists in your `datamodel.prisma` file. And do not forget to deploy it before starting the server again:
```
prisma deploy
```
