### ISSUE TITLE
I got a error when i run the local instance

### ISSUE THREAD

**Issue by sessionboy** [howtographql/howtographql#850]
I follow this:
```
  git clone git@github.com:howtographql/howtographql.git
  cd howtographql
  yarn install
  yarn start
```
But i got the error:
```
UNHANDLED REJECTION Error: RootQueryType.allSitePage field type must be Output Type but got: SitePageConnection
```

**Comment by swcarlosrj** [comment]
Thanks @sessionboy for opening this issue 😄. it should be fixed. Closing this!

**Comment by sessionboy** [comment]
@swcarlosrj  Has the problem been fixed ? I still can't run the project.
```js
UNHANDLED REJECTION Error: RootQueryType.allSitePage field type must be Output Type but got: SitePageConnection
```

**Comment by ztana** [comment]
@sessionboy did you run successful eventually?
